services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT_HOST}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_INITDB_ROOT_USERNAME}", "--password", "${MONGO_INITDB_ROOT_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.runCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT_HOST}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_PORT: ${VITE_PORT}
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "${VITE_PORT_HOST}:${VITE_PORT}"
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  mongo-data:
